# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Coder For Fun | Xingfan's Tech Blog
subtitle: Random Stuff Randonly Updated
description:
author: Xingfan Xia
language: en
timezone: America/Chicago
avatar: https://7xqpdw.com1.z0.glb.clouddn.com/321_55f4fb5bc15dd.jpg


# Disqus
disqus_shortname: xingfanstechblog

#Google Analytics
google_analytics: UA-65724730-3

#social
social:
  cv: https://xiax.dev
  github: https://github.com/xingfanxia
  twitter: https://twitter.com/your-user-name
  weibo: http://weibo.com/your-user-name
  douban: http://douban.com/people/your-user-name
  zhihu: http://www.zhihu.com/people/your-user-name

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.xiax.dev
root: /
permalink: :year/:month/:day/:title.html/
permalink_defaults:


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [skip/*]

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next

sitemap:
    path: sitemap.xml

math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: custom_mathjax_source
    config:
      # MathJax config
  katex:
    css: custom_css_source
    js: custom_js_source # not used
    config:
      # KaTeX config

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: s3
  bucket: blog.xiax.dev
  aws_cli_profile: personal
  region: us-west-1
  headers: {CacheControl: 'max-age=604800, public'}